### ISSUE TITLE
Get problem when I try to run the code following the instruction. 

### ISSUE THREAD

**Issue by suncj** [fmchowdhury/HyREX#1]
Following are output information. Besides, where should I find the bioRelEx.jar in the JVM_ARGS. Thanks a lot.

bash-3.2$ ./hyrex_run.sh 
Mon Apr 14 17:46:09 EDT 2014 started running the script .....
Mon Apr 14 17:46:09 EDT 2014 started running the script .....
-medtType 6 -trainParse /Users/labuser/Downloads/HyREX-master/sample-data/sample.parsed.bllip.complete -train /Users/labuser/Downloads/HyREX-master/sample-data/sample.full -testParse /Users/labuser/Downloads/HyREX-master/sample-data/sample.parsed.bllip.complete -test /Users/labuser/Downloads/HyREX-master/sample-data/sample.full -nf 1 -trigFile /Users/labuser/Downloads/HyREX-master/db/ddi_trigger -classifySentences
Exception in thread "main" java.io.FileNotFoundException: out/allSenIdsForTest (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
    at java.io.FileWriter.<init>(FileWriter.java:61)
    at Utility.FileUtility.writeInFile(FileUtility.java:225)
    at Kernels.TKOutputGenerator.main(TKOutputGenerator.java:140)
./hyrex_run.sh: line 118: /Users/labuser/Downloads/HyREX-master/out/trace: No such file or directory
hyrex_sen_run.sh: line 12: /Users/labuser/Downloads/HyREX-master/out/trace: No such file or directory
rm: /Users/labuser/Downloads/HyREX-master/out/output.txt: No such file or directory
rm: /Users/labuser/Downloads/HyREX-master/out/trace: No such file or directory
rm: /Users/labuser/Downloads/HyREX-master/SVM-Light-TK-1.5/svm_predictions: No such file or directory
rm: /Users/labuser/Downloads/HyREX-master/out/base.stat.in_ddi_sen: No such file or directory
grep: /Users/labuser/Downloads/HyREX-master/out/train.tk: No such file or directory
grep: /Users/labuser/Downloads/HyREX-master/out/train.tk: No such file or directory
No of positive instance is zero. Aborting training.
-pst -jsre -wv -kjsre SL -medtType 6 -trainParse /Users/labuser/Downloads/HyREX-master/sample-data/sample.parsed.bllip.complete -train /Users/labuser/Downloads/HyREX-master/sample-data/sample.full -testParse /Users/labuser/Downloads/HyREX-master/sample-data/sample.parsed.bllip.complete -test /Users/labuser/Downloads/HyREX-master/sample-data/sample.full -nf 1 -trigFile /Users/labuser/Downloads/HyREX-master/db/ddi_trigger
Exception in thread "main" java.io.FileNotFoundException: out/allEntPair (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
    at java.io.FileWriter.<init>(FileWriter.java:61)
    at Utility.FileUtility.writeInFile(FileUtility.java:225)
    at Structures.Sentence.readFullData(Sentence.java:442)
    at Structures.Sentence.readFullData(Sentence.java:372)
    at Kernels.TKOutputGenerator.main(TKOutputGenerator.java:159)
hyrex_sen_run.sh: line 12: /Users/labuser/Downloads/HyREX-master/out/trace: No such file or directory
rm: /Users/labuser/Downloads/HyREX-master/out/output.txt: No such file or directory
rm: /Users/labuser/Downloads/HyREX-master/out/trace: No such file or directory
rm: /Users/labuser/Downloads/HyREX-master/SVM-Light-TK-1.5/svm_predictions: No such file or directory
rm: /Users/labuser/Downloads/HyREX-master/out/base.stat.in: No such file or directory
grep: /Users/labuser/Downloads/HyREX-master/out/train.tk: No such file or directory
grep: /Users/labuser/Downloads/HyREX-master/out/train.tk: No such file or directory
No of positive instance is zero. Aborting training.

**Comment by fmchowdhury** [comment]
Hi, you don't need `bioRelEx.jar`. Please take the updated `.sh` files and run. 

The exception that you were getting was due to missing "out" folder. The ".sh" file will now create the folder if it is not present.

Thanks.
